package Entidades;
// Generated 01/04/2018 17:54:30 by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private int edad;

    public Persona() {
    }

    public Persona(String nombre, String apellido, int edad) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    
     @Override
    public String toString()
    {
        return this.id+" "+this.nombre+" "+this.apellido+" "+this.edad;
    }




}


