/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author alumno
 */
public class frmCComercial extends javax.swing.JFrame {

    /**
     * Creates new form frmCComercial
     */
    public frmCComercial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpNuevoCComercial = new javax.swing.JPanel();
        jlNombreCComercial = new javax.swing.JLabel();
        jtfNombreCComercial = new javax.swing.JTextField();
        btnCComercialAgregar = new javax.swing.JButton();
        btnCComercialSalir = new javax.swing.JButton();
        jpCComercialModificar = new javax.swing.JPanel();
        jlCComercial = new javax.swing.JLabel();
        cbCentrosComerciales = new javax.swing.JComboBox<>();
        jlNuevoNombre = new javax.swing.JLabel();
        tfNuevoNombre = new javax.swing.JTextField();
        btnCComercialModificar = new javax.swing.JButton();
        btnCComercialSalirModificar = new javax.swing.JButton();
        jpCComercialBorrar = new javax.swing.JPanel();
        jlCComercialBorrar = new javax.swing.JLabel();
        cbSeleccionarCComercial = new javax.swing.JComboBox<>();
        bnBorrarBorrar = new javax.swing.JButton();
        btnSalirBorrar = new javax.swing.JButton();
        jpCComercialMostrar = new javax.swing.JPanel();
        jlCComercialMostrarCiudad = new javax.swing.JLabel();
        cbCiudades = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlCComercialLista = new javax.swing.JList<>();
        btnMostrarSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpNuevoCComercial.setVisible(false);

        jlNombreCComercial.setText("Nombre:");

        btnCComercialAgregar.setText("Agregar");

        btnCComercialSalir.setText("Salir");
        btnCComercialSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCComercialSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpNuevoCComercialLayout = new javax.swing.GroupLayout(jpNuevoCComercial);
        jpNuevoCComercial.setLayout(jpNuevoCComercialLayout);
        jpNuevoCComercialLayout.setHorizontalGroup(
            jpNuevoCComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNuevoCComercialLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jlNombreCComercial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNombreCComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpNuevoCComercialLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnCComercialAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCComercialSalir)
                .addGap(20, 20, 20))
        );
        jpNuevoCComercialLayout.setVerticalGroup(
            jpNuevoCComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNuevoCComercialLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpNuevoCComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreCComercial)
                    .addComponent(jtfNombreCComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jpNuevoCComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCComercialAgregar)
                    .addComponent(btnCComercialSalir))
                .addGap(26, 26, 26))
        );

        jpCComercialModificar.setVisible(false);

        jlCComercial.setText("Centro Comercial: ");

        cbCentrosComerciales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlNuevoNombre.setText("Nuevo nombre");

        btnCComercialModificar.setText("Modificar");

        btnCComercialSalirModificar.setText("Salir");
        btnCComercialSalirModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCComercialSalirModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCComercialModificarLayout = new javax.swing.GroupLayout(jpCComercialModificar);
        jpCComercialModificar.setLayout(jpCComercialModificarLayout);
        jpCComercialModificarLayout.setHorizontalGroup(
            jpCComercialModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCComercialModificarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpCComercialModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCComercialModificar)
                    .addGroup(jpCComercialModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlCComercial)
                        .addComponent(jlNuevoNombre)))
                .addGroup(jpCComercialModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCComercialModificarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpCComercialModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbCentrosComerciales, 0, 133, Short.MAX_VALUE)
                            .addComponent(tfNuevoNombre))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCComercialModificarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(btnCComercialSalirModificar)
                        .addGap(58, 58, 58))))
        );
        jpCComercialModificarLayout.setVerticalGroup(
            jpCComercialModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCComercialModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCComercialModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCComercial)
                    .addComponent(cbCentrosComerciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCComercialModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNuevoNombre)
                    .addComponent(tfNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCComercialModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCComercialModificar)
                    .addComponent(btnCComercialSalirModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCComercialBorrar.setVisible(false);

        jlCComercialBorrar.setText("Centro Comercial:");

        cbSeleccionarCComercial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bnBorrarBorrar.setText("Borrar");

        btnSalirBorrar.setText("Salir");
        btnSalirBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCComercialBorrarLayout = new javax.swing.GroupLayout(jpCComercialBorrar);
        jpCComercialBorrar.setLayout(jpCComercialBorrarLayout);
        jpCComercialBorrarLayout.setHorizontalGroup(
            jpCComercialBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCComercialBorrarLayout.createSequentialGroup()
                .addGroup(jpCComercialBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCComercialBorrarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jlCComercialBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(cbSeleccionarCComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCComercialBorrarLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(bnBorrarBorrar)
                        .addGap(62, 62, 62)
                        .addComponent(btnSalirBorrar)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jpCComercialBorrarLayout.setVerticalGroup(
            jpCComercialBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCComercialBorrarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpCComercialBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCComercialBorrar)
                    .addComponent(cbSeleccionarCComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jpCComercialBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnBorrarBorrar)
                    .addComponent(btnSalirBorrar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jpCComercialMostrar.setVisible(false);

        jlCComercialMostrarCiudad.setText("Ciudad:");

        cbCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlCComercialLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlCComercialLista);

        btnMostrarSalir.setText("Salir");
        btnMostrarSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCComercialMostrarLayout = new javax.swing.GroupLayout(jpCComercialMostrar);
        jpCComercialMostrar.setLayout(jpCComercialMostrarLayout);
        jpCComercialMostrarLayout.setHorizontalGroup(
            jpCComercialMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCComercialMostrarLayout.createSequentialGroup()
                .addGroup(jpCComercialMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCComercialMostrarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlCComercialMostrarCiudad)
                        .addGap(18, 18, 18)
                        .addComponent(cbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCComercialMostrarLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCComercialMostrarLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnMostrarSalir)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jpCComercialMostrarLayout.setVerticalGroup(
            jpCComercialMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCComercialMostrarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpCComercialMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCComercialMostrarCiudad)
                    .addComponent(cbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarSalir)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpNuevoCComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jpCComercialModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jpCComercialBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpCComercialMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpCComercialModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jpNuevoCComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jpCComercialMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpCComercialBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCComercialSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCComercialSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnCComercialSalirActionPerformed

    private void btnCComercialSalirModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCComercialSalirModificarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCComercialSalirModificarActionPerformed

    private void btnSalirBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirBorrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirBorrarActionPerformed

    private void btnMostrarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnMostrarSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCComercial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnBorrarBorrar;
    private javax.swing.JButton btnCComercialAgregar;
    private javax.swing.JButton btnCComercialModificar;
    private javax.swing.JButton btnCComercialSalir;
    private javax.swing.JButton btnCComercialSalirModificar;
    private javax.swing.JButton btnMostrarSalir;
    private javax.swing.JButton btnSalirBorrar;
    private javax.swing.JComboBox<String> cbCentrosComerciales;
    private javax.swing.JComboBox<String> cbCiudades;
    private javax.swing.JComboBox<String> cbSeleccionarCComercial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlCComercial;
    private javax.swing.JLabel jlCComercialBorrar;
    private javax.swing.JList<String> jlCComercialLista;
    private javax.swing.JLabel jlCComercialMostrarCiudad;
    private javax.swing.JLabel jlNombreCComercial;
    private javax.swing.JLabel jlNuevoNombre;
    public static javax.swing.JPanel jpCComercialBorrar;
    public static javax.swing.JPanel jpCComercialModificar;
    public static javax.swing.JPanel jpCComercialMostrar;
    public static javax.swing.JPanel jpNuevoCComercial;
    private javax.swing.JTextField jtfNombreCComercial;
    private javax.swing.JTextField tfNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
