/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class frmVistaGeneral extends javax.swing.JFrame {

    JFrame formulario;
    JPanel panel;
    /**
     * Creates new form njfVistaGeneral
     */
    public frmVistaGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jpCComercial = new javax.swing.JPanel();
        jmbMenu = new javax.swing.JMenuBar();
        jmCComercial = new javax.swing.JMenu();
        jmiNuevoCComercial = new javax.swing.JMenuItem();
        jmiModificar = new javax.swing.JMenuItem();
        jmiBorrar = new javax.swing.JMenuItem();
        jmiMostrarCComercial = new javax.swing.JMenuItem();
        jmCines = new javax.swing.JMenu();
        jmiNuevoCine = new javax.swing.JMenuItem();
        jmiModificarCine = new javax.swing.JMenuItem();
        jmiBorrarCine = new javax.swing.JMenuItem();
        jmiMostrarCines = new javax.swing.JMenuItem();
        jmSalas = new javax.swing.JMenu();
        jmiNuevaSala = new javax.swing.JMenuItem();
        jmiModificarSala = new javax.swing.JMenuItem();
        jmiBorrarSala = new javax.swing.JMenuItem();
        jmiMostrarSalas = new javax.swing.JMenuItem();
        jmiMostrarLugaresLibres = new javax.swing.JMenuItem();
        jmFunciones = new javax.swing.JMenu();
        jmiNuevaFuncion = new javax.swing.JMenuItem();
        jmiModificarFuncion = new javax.swing.JMenuItem();
        jmiBorrarFuncion = new javax.swing.JMenuItem();
        jmiMostrarFunciones = new javax.swing.JMenuItem();
        jmEntradas = new javax.swing.JMenu();
        jmiVenderEntradas = new javax.swing.JMenuItem();
        jmiConteoDeVentas = new javax.swing.JMenuItem();
        jmPeliculas = new javax.swing.JMenu();
        jmiAgregarPelicula = new javax.swing.JMenuItem();
        jmiMostrarPeliculas = new javax.swing.JMenuItem();
        jmiBorrarPelicula = new javax.swing.JMenuItem();
        jmiModificarPelicula = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jpCComercialLayout = new javax.swing.GroupLayout(jpCComercial);
        jpCComercial.setLayout(jpCComercialLayout);
        jpCComercialLayout.setHorizontalGroup(
            jpCComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        jpCComercialLayout.setVerticalGroup(
            jpCComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jmCComercial.setText("C. Comercial");

        jmiNuevoCComercial.setText("Nuevo C.Comercial");
        jmiNuevoCComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoCComercialActionPerformed(evt);
            }
        });
        jmCComercial.add(jmiNuevoCComercial);

        jmiModificar.setText("Modificar");
        jmiModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarActionPerformed(evt);
            }
        });
        jmCComercial.add(jmiModificar);

        jmiBorrar.setText("Borrar");
        jmiBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarActionPerformed(evt);
            }
        });
        jmCComercial.add(jmiBorrar);

        jmiMostrarCComercial.setText("Mostrar");
        jmiMostrarCComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarCComercialActionPerformed(evt);
            }
        });
        jmCComercial.add(jmiMostrarCComercial);

        jmbMenu.add(jmCComercial);

        jmCines.setText("Cines");

        jmiNuevoCine.setText("Nuevo");
        jmiNuevoCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoCineActionPerformed(evt);
            }
        });
        jmCines.add(jmiNuevoCine);

        jmiModificarCine.setText("Modificar");
        jmCines.add(jmiModificarCine);

        jmiBorrarCine.setText("Borrar");
        jmCines.add(jmiBorrarCine);

        jmiMostrarCines.setText("Mostrar");
        jmCines.add(jmiMostrarCines);

        jmbMenu.add(jmCines);

        jmSalas.setText("Salas");

        jmiNuevaSala.setText("Nueva sala");
        jmiNuevaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevaSalaActionPerformed(evt);
            }
        });
        jmSalas.add(jmiNuevaSala);

        jmiModificarSala.setText("Modificar");
        jmiModificarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarSalaActionPerformed(evt);
            }
        });
        jmSalas.add(jmiModificarSala);

        jmiBorrarSala.setText("Borrar");
        jmSalas.add(jmiBorrarSala);

        jmiMostrarSalas.setText("Mostrar salas");
        jmSalas.add(jmiMostrarSalas);

        jmiMostrarLugaresLibres.setText("Mostrar lugares libres");
        jmSalas.add(jmiMostrarLugaresLibres);

        jmbMenu.add(jmSalas);

        jmFunciones.setText("Funciones");

        jmiNuevaFuncion.setText("Nueva funcion");
        jmFunciones.add(jmiNuevaFuncion);

        jmiModificarFuncion.setText("Modificar");
        jmFunciones.add(jmiModificarFuncion);

        jmiBorrarFuncion.setText("Borrar");
        jmFunciones.add(jmiBorrarFuncion);

        jmiMostrarFunciones.setText("Mostrar funciones");
        jmFunciones.add(jmiMostrarFunciones);

        jmbMenu.add(jmFunciones);

        jmEntradas.setText("Entradas");

        jmiVenderEntradas.setText("Vender entradas");
        jmEntradas.add(jmiVenderEntradas);

        jmiConteoDeVentas.setText("Conteo de ventas");
        jmEntradas.add(jmiConteoDeVentas);

        jmbMenu.add(jmEntradas);

        jmPeliculas.setText("Peliculas");

        jmiAgregarPelicula.setText("Agregar pelicula");
        jmPeliculas.add(jmiAgregarPelicula);

        jmiMostrarPeliculas.setText("Mostrar peliculas");
        jmPeliculas.add(jmiMostrarPeliculas);

        jmiBorrarPelicula.setText("Borrar pelicula");
        jmPeliculas.add(jmiBorrarPelicula);

        jmiModificarPelicula.setText("Modificar pelicula");
        jmiModificarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarPeliculaActionPerformed(evt);
            }
        });
        jmPeliculas.add(jmiModificarPelicula);

        jmbMenu.add(jmPeliculas);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jpCComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jpCComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiModificarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiModificarSalaActionPerformed

    private void jmiNuevaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevaSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiNuevaSalaActionPerformed

    private void jmiModificarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiModificarPeliculaActionPerformed

    
    public void VerificarVisibilidadFormulario()
    {
        if(this.formulario!=null)
        {
            this.formulario.setVisible(false);
        }
        
    }
    
    public void InstanciarFormularioCComercial()
    {
        this.formulario=new frmCComercial();
        this.formulario.setVisible(true);
    }
    
    public void VerificarVisibilidadPanel()
    {
        if(this.panel!=null)
        {
            this.panel.setVisible(true);
        }
    }
    
    
    private void jmiNuevoCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoCineActionPerformed
        // TODO add your handling code here:
        frmCine frm = new frmCine();
        frm.setVisible(true);
    }//GEN-LAST:event_jmiNuevoCineActionPerformed

    private void jmiNuevoCComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoCComercialActionPerformed
        // TODO add your handling code here:
        
        //this.formulario= new frmCComercial();
        //verificar si hay un formulario activo
        //VerificarVisibilidadFormulario();
        
        InstanciarFormularioCComercial();
        //verifica si hay un panel visible en el formulario
        //VerificarVisibilidadPanel();
        frmCComercial.jpNuevoCComercial.setVisible(true);

    }//GEN-LAST:event_jmiNuevoCComercialActionPerformed

    private void jmiModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarActionPerformed
        // TODO add your handling code here:
        InstanciarFormularioCComercial();
        //VerificarVisibilidadPanel();
        frmCComercial.jpCComercialModificar.setVisible(true);
        
    }//GEN-LAST:event_jmiModificarActionPerformed

    private void jmiBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarActionPerformed
        
        InstanciarFormularioCComercial();
       // VerificarVisibilidadPanel();
       frmCComercial.jpCComercialBorrar.setVisible(true);
        
    }//GEN-LAST:event_jmiBorrarActionPerformed

    private void jmiMostrarCComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarCComercialActionPerformed
        InstanciarFormularioCComercial();
        frmCComercial.jpCComercialModificar.setVisible(true);
        
    }//GEN-LAST:event_jmiMostrarCComercialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVistaGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmCComercial;
    private javax.swing.JMenu jmCines;
    private javax.swing.JMenu jmEntradas;
    private javax.swing.JMenu jmFunciones;
    private javax.swing.JMenu jmPeliculas;
    private javax.swing.JMenu jmSalas;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiAgregarPelicula;
    private javax.swing.JMenuItem jmiBorrar;
    private javax.swing.JMenuItem jmiBorrarCine;
    private javax.swing.JMenuItem jmiBorrarFuncion;
    private javax.swing.JMenuItem jmiBorrarPelicula;
    private javax.swing.JMenuItem jmiBorrarSala;
    private javax.swing.JMenuItem jmiConteoDeVentas;
    private javax.swing.JMenuItem jmiModificar;
    private javax.swing.JMenuItem jmiModificarCine;
    private javax.swing.JMenuItem jmiModificarFuncion;
    private javax.swing.JMenuItem jmiModificarPelicula;
    private javax.swing.JMenuItem jmiModificarSala;
    private javax.swing.JMenuItem jmiMostrarCComercial;
    private javax.swing.JMenuItem jmiMostrarCines;
    private javax.swing.JMenuItem jmiMostrarFunciones;
    private javax.swing.JMenuItem jmiMostrarLugaresLibres;
    private javax.swing.JMenuItem jmiMostrarPeliculas;
    private javax.swing.JMenuItem jmiMostrarSalas;
    private javax.swing.JMenuItem jmiNuevaFuncion;
    private javax.swing.JMenuItem jmiNuevaSala;
    private javax.swing.JMenuItem jmiNuevoCComercial;
    private javax.swing.JMenuItem jmiNuevoCine;
    private javax.swing.JMenuItem jmiVenderEntradas;
    private javax.swing.JPanel jpCComercial;
    // End of variables declaration//GEN-END:variables
}
