package Entidades;
// Generated 28-mar-2018 13:10:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Butaca generated by hbm2java
 */
public class Butaca  implements java.io.Serializable {


     private Integer idbutaca;
     private Salacine salacine;
     private String butacaTipoButaca;
     private Set entradas = new HashSet(0);

    public Butaca() {
    }

	
    public Butaca(Salacine salacine, String butacaTipoButaca) {
        this.salacine = salacine;
        this.butacaTipoButaca = butacaTipoButaca;
    }
    public Butaca(Salacine salacine, String butacaTipoButaca, Set entradas) {
       this.salacine = salacine;
       this.butacaTipoButaca = butacaTipoButaca;
       this.entradas = entradas;
    }
   
    public Integer getIdbutaca() {
        return this.idbutaca;
    }
    
    public void setIdbutaca(Integer idbutaca) {
        this.idbutaca = idbutaca;
    }
    public Salacine getSalacine() {
        return this.salacine;
    }
    
    public void setSalacine(Salacine salacine) {
        this.salacine = salacine;
    }
    public String getButacaTipoButaca() {
        return this.butacaTipoButaca;
    }
    
    public void setButacaTipoButaca(String butacaTipoButaca) {
        this.butacaTipoButaca = butacaTipoButaca;
    }
    public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }




}


