package Entidades;
// Generated 03/04/2018 16:15:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CentroComercial generated by hbm2java
 */
public class CentroComercial  implements java.io.Serializable {


     private Integer idCentroComercial;
     private String centroComercialNombre;
     private Set cines = new HashSet(0);

    public CentroComercial() {
    }
    
    public CentroComercial(int id)
    {
        this.idCentroComercial=id;
    }
	
    public CentroComercial(String centroComercialNombre) {
        this.centroComercialNombre = centroComercialNombre;
    }
    public CentroComercial(String centroComercialNombre, Set cines) {
       this.centroComercialNombre = centroComercialNombre;
       this.cines = cines;
    }
   
    public Integer getIdCentroComercial() {
        return this.idCentroComercial;
    }
    
    public void setIdCentroComercial(Integer idCentroComercial) {
        this.idCentroComercial = idCentroComercial;
    }
    public String getCentroComercialNombre() {
        return this.centroComercialNombre;
    }
    
    public void setCentroComercialNombre(String centroComercialNombre) {
        this.centroComercialNombre = centroComercialNombre;
    }
    public Set getCines() {
        return this.cines;
    }
    
    public void setCines(Set cines) {
        this.cines = cines;
    }




}


