package Entidades;
// Generated 03/04/2018 16:15:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cine generated by hbm2java
 */
public class Cine  implements java.io.Serializable {


     private Integer idCine;
     private CentroComercial centroComercial;
     private String cineNombre;
     private Set salacines = new HashSet(0);

    public Cine() {
    }

	
    public Cine(CentroComercial centroComercial, String cineNombre) {
        this.centroComercial = centroComercial;
        this.cineNombre = cineNombre;
    }
    public Cine(CentroComercial centroComercial, String cineNombre, Set salacines) {
       this.centroComercial = centroComercial;
       this.cineNombre = cineNombre;
       this.salacines = salacines;
    }
   
    public Integer getIdCine() {
        return this.idCine;
    }
    
    public void setIdCine(Integer idCine) {
        this.idCine = idCine;
    }
    public CentroComercial getCentroComercial() {
        return this.centroComercial;
    }
    
    public void setCentroComercial(CentroComercial centroComercial) {
        this.centroComercial = centroComercial;
    }
    public String getCineNombre() {
        return this.cineNombre;
    }
    
    public void setCineNombre(String cineNombre) {
        this.cineNombre = cineNombre;
    }
    public Set getSalacines() {
        return this.salacines;
    }
    
    public void setSalacines(Set salacines) {
        this.salacines = salacines;
    }




}


