package Entidades;
// Generated 03/04/2018 16:15:58 by Hibernate Tools 4.3.1



/**
 * Entrada generated by hbm2java
 */
public class Entrada  implements java.io.Serializable {


     private Integer idEntrada;
     private Butaca butaca;
     private Funcion funcion;

    public Entrada() {
    }

    public Entrada(Butaca butaca, Funcion funcion) {
       this.butaca = butaca;
       this.funcion = funcion;
    }
   
    public Integer getIdEntrada() {
        return this.idEntrada;
    }
    
    public void setIdEntrada(Integer idEntrada) {
        this.idEntrada = idEntrada;
    }
    public Butaca getButaca() {
        return this.butaca;
    }
    
    public void setButaca(Butaca butaca) {
        this.butaca = butaca;
    }
    public Funcion getFuncion() {
        return this.funcion;
    }
    
    public void setFuncion(Funcion funcion) {
        this.funcion = funcion;
    }




}


