package Entidades;
// Generated 28-mar-2018 13:10:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private int idPelicula;
     private String peliculaNombre;
     private String peliculaDuracion;
     private String peliculaEdadMinima;
     private Set funcions = new HashSet(0);

    public Pelicula() {
    }

	
    public Pelicula(int idPelicula, String peliculaNombre, String peliculaDuracion, String peliculaEdadMinima) {
        this.idPelicula = idPelicula;
        this.peliculaNombre = peliculaNombre;
        this.peliculaDuracion = peliculaDuracion;
        this.peliculaEdadMinima = peliculaEdadMinima;
    }
    public Pelicula(int idPelicula, String peliculaNombre, String peliculaDuracion, String peliculaEdadMinima, Set funcions) {
       this.idPelicula = idPelicula;
       this.peliculaNombre = peliculaNombre;
       this.peliculaDuracion = peliculaDuracion;
       this.peliculaEdadMinima = peliculaEdadMinima;
       this.funcions = funcions;
    }
   
    public int getIdPelicula() {
        return this.idPelicula;
    }
    
    public void setIdPelicula(int idPelicula) {
        this.idPelicula = idPelicula;
    }
    public String getPeliculaNombre() {
        return this.peliculaNombre;
    }
    
    public void setPeliculaNombre(String peliculaNombre) {
        this.peliculaNombre = peliculaNombre;
    }
    public String getPeliculaDuracion() {
        return this.peliculaDuracion;
    }
    
    public void setPeliculaDuracion(String peliculaDuracion) {
        this.peliculaDuracion = peliculaDuracion;
    }
    public String getPeliculaEdadMinima() {
        return this.peliculaEdadMinima;
    }
    
    public void setPeliculaEdadMinima(String peliculaEdadMinima) {
        this.peliculaEdadMinima = peliculaEdadMinima;
    }
    public Set getFuncions() {
        return this.funcions;
    }
    
    public void setFuncions(Set funcions) {
        this.funcions = funcions;
    }




}


