package Entidades;
// Generated 28-mar-2018 13:10:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private int idTipo;
     private String tipoNombre;
     private Set funcions = new HashSet(0);

    public Tipo() {
    }

	
    public Tipo(int idTipo, String tipoNombre) {
        this.idTipo = idTipo;
        this.tipoNombre = tipoNombre;
    }
    public Tipo(int idTipo, String tipoNombre, Set funcions) {
       this.idTipo = idTipo;
       this.tipoNombre = tipoNombre;
       this.funcions = funcions;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getTipoNombre() {
        return this.tipoNombre;
    }
    
    public void setTipoNombre(String tipoNombre) {
        this.tipoNombre = tipoNombre;
    }
    public Set getFuncions() {
        return this.funcions;
    }
    
    public void setFuncions(Set funcions) {
        this.funcions = funcions;
    }




}


