/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Juego;
import Entidades.Jugadas;
import Entidades.Jugador;
import Enumerados.TipoDeJuego;
import dao.juegoDao;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author alumno
 */
public class frmVistaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmVistaUsuario
     */
    public frmVistaUsuario() {
        initComponents();
        cbJugador.removeAllItems();
        cbJuego.removeAllItems();
        cbTipoDeJuego.removeAllItems();
        
        
        this.cargarComboJugador();

        this.cargarComboJuego();
        
        this.cargarComboTipoJuego();
    }
    
    public void cargarListadoTabla(){
    DefaultListModel modelo = new DefaultListModel();
    tbListado.setModel((TableModel) modelo);
    
        List datos=Jugadas.listarJugadas();
        Iterator iter= datos.iterator();
        
        while(iter.hasNext()){
              Jugadas j= (Jugadas)iter.next();
              
              //modelo.addElement();
        }
        
        
    }
    
    
    
    public void cargarComboTipoJuego(){
        //asi se carga un tipo de enumerados en un combo box.
        for (TipoDeJuego  tipo: TipoDeJuego.values()) {
            cbTipoDeJuego.addItem(tipo.toString());
        }
        
    }   
    public void cargarComboJugador() {
        ArrayList<String> lista = new ArrayList<String>();
        lista = Jugador.retornarJugador();
        for (int i = 0; i < lista.size(); i++) {
            cbJugador.addItem(lista.get(i));
        }
    }

    public void cargarComboJuego() {
        ArrayList<String> listaJuegos = new ArrayList<String>();
        listaJuegos = Juego.retornarListaJuegos();
        for (int i = 0; i < listaJuegos.size(); i++) {
            cbJuego.addItem(listaJuegos.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoResultado = new javax.swing.ButtonGroup();
        grupoAscDesc = new javax.swing.ButtonGroup();
        cbJugador = new javax.swing.JComboBox<>();
        cbJuego = new javax.swing.JComboBox<>();
        cbTipoDeJuego = new javax.swing.JComboBox<>();
        btnTraer = new javax.swing.JButton();
        rbtnGano = new javax.swing.JRadioButton();
        rbtnPerdio = new javax.swing.JRadioButton();
        rbtnEmpato = new javax.swing.JRadioButton();
        rbtnTodos = new javax.swing.JRadioButton();
        rbtnAsc = new javax.swing.JRadioButton();
        rbtnDesc = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListado = new javax.swing.JTable();

        cbJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTipoDeJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTraer.setText("Traer");

        grupoResultado.add(rbtnGano);
        rbtnGano.setText("Gano");

        grupoResultado.add(rbtnPerdio);
        rbtnPerdio.setText("Perdio");

        grupoResultado.add(rbtnEmpato);
        rbtnEmpato.setText("Empato");

        grupoResultado.add(rbtnTodos);
        rbtnTodos.setText("Todos");

        grupoAscDesc.add(rbtnAsc);
        rbtnAsc.setText("Ascendente");

        grupoAscDesc.add(rbtnDesc);
        rbtnDesc.setText("Descendente");

        tbListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbListado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(cbJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(cbTipoDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTraer)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnAsc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnDesc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnGano)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnPerdio)
                                .addGap(21, 21, 21)
                                .addComponent(rbtnEmpato)))
                        .addGap(28, 28, 28)
                        .addComponent(rbtnTodos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTraer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnGano)
                    .addComponent(rbtnPerdio)
                    .addComponent(rbtnEmpato)
                    .addComponent(rbtnTodos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnAsc)
                    .addComponent(rbtnDesc))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraer;
    private javax.swing.JComboBox<String> cbJuego;
    private javax.swing.JComboBox<String> cbJugador;
    private javax.swing.JComboBox<String> cbTipoDeJuego;
    private javax.swing.ButtonGroup grupoAscDesc;
    private javax.swing.ButtonGroup grupoResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnAsc;
    private javax.swing.JRadioButton rbtnDesc;
    private javax.swing.JRadioButton rbtnEmpato;
    private javax.swing.JRadioButton rbtnGano;
    private javax.swing.JRadioButton rbtnPerdio;
    private javax.swing.JRadioButton rbtnTodos;
    private javax.swing.JTable tbListado;
    // End of variables declaration//GEN-END:variables
}
