/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Juego;
import Entidades.Jugadas;
import Entidades.Jugador;
import Enumerados.TipoDeResultado;
import dao.conexion;
import dao.juegoDao;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumno
 */
public class JFVistaUsuario extends javax.swing.JFrame {

    ResultSet rs;

    /**
     * Creates new form JFVistaUsuario
     */
    public JFVistaUsuario() {
        initComponents();
        cbJugador.removeAllItems();
        cbJuego.removeAllItems();
        cbTipoDeJuego.removeAllItems();

        this.cargarComboJugador();

        this.cargarComboJuego();

        this.cargarTablaJugadas();
    }

    public void cargarTablaJugadas() {
        DefaultTableModel modelo = new DefaultTableModel();
        tbListado.setModel(modelo);

        modelo.addColumn("IdJugada");
        modelo.addColumn("Juego_idJuego");
        modelo.addColumn("Jugador_idJugador");
        modelo.addColumn("resultado");
        
        ArrayList<Object> lista=Jugadas.listarJugadas();
        Iterator iter= lista.iterator();
        
        while(iter.hasNext()){
            Jugadas jugada= (Jugadas)iter.next();
            
            Object[] fila= new Object[4];
            fila[0]=jugada.getId();
            fila[1]=jugada.getJuego();
            fila[2]=jugada.getJugador();
            fila[3]=jugada.getResultado();
        
        modelo.addRow(fila);
        }

    }

    public void cargarComboJugador() {
        ArrayList<String> lista = new ArrayList<String>();
        lista = Jugador.retornarJugador();
        for (int i = 0; i < lista.size(); i++) {
            cbJugador.addItem(lista.get(i));
        }
    }

    public void cargarComboJuego() {
        ArrayList<String> listaJuegos = new ArrayList<String>();
        listaJuegos = Juego.retornarListaJuegos();
        for (int i = 0; i < listaJuegos.size(); i++) {
            cbJuego.addItem(listaJuegos.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoResultados = new javax.swing.ButtonGroup();
        btnGrupoAscDesc = new javax.swing.ButtonGroup();
        cbJugador = new javax.swing.JComboBox<>();
        cbJuego = new javax.swing.JComboBox<>();
        cbTipoDeJuego = new javax.swing.JComboBox<>();
        btnTraer = new javax.swing.JButton();
        rbtnGano = new javax.swing.JRadioButton();
        rbtnPerdio = new javax.swing.JRadioButton();
        rbtnEmpato = new javax.swing.JRadioButton();
        rbtnTodos = new javax.swing.JRadioButton();
        rbtnDesc = new javax.swing.JRadioButton();
        rbtnAsc = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJugadorActionPerformed(evt);
            }
        });

        cbJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTipoDeJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTraer.setText("Traer");

        btnGrupoResultados.add(rbtnGano);
        rbtnGano.setText("Gano");

        btnGrupoResultados.add(rbtnPerdio);
        rbtnPerdio.setText("Perdio");

        btnGrupoResultados.add(rbtnEmpato);
        rbtnEmpato.setText("Empato");

        btnGrupoResultados.add(rbtnTodos);
        rbtnTodos.setText("Todos");

        btnGrupoAscDesc.add(rbtnDesc);
        rbtnDesc.setText("Desc");

        btnGrupoAscDesc.add(rbtnAsc);
        rbtnAsc.setText("Asc");
        rbtnAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAscActionPerformed(evt);
            }
        });

        tbListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbListado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnGano)
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnEmpato)
                            .addComponent(rbtnAsc))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnDesc)
                            .addComponent(rbtnTodos))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnPerdio))
                .addGap(36, 36, 36)
                .addComponent(cbTipoDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTraer)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTraer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTodos)
                    .addComponent(rbtnEmpato)
                    .addComponent(rbtnPerdio)
                    .addComponent(rbtnGano))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnAsc)
                    .addComponent(rbtnDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAscActionPerformed

    private void cbJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJugadorActionPerformed

    }//GEN-LAST:event_cbJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVistaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupoAscDesc;
    private javax.swing.ButtonGroup btnGrupoResultados;
    private javax.swing.JButton btnTraer;
    private javax.swing.JComboBox<String> cbJuego;
    private javax.swing.JComboBox<String> cbJugador;
    private javax.swing.JComboBox<String> cbTipoDeJuego;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnAsc;
    private javax.swing.JRadioButton rbtnDesc;
    private javax.swing.JRadioButton rbtnEmpato;
    private javax.swing.JRadioButton rbtnGano;
    private javax.swing.JRadioButton rbtnPerdio;
    private javax.swing.JRadioButton rbtnTodos;
    private javax.swing.JTable tbListado;
    // End of variables declaration//GEN-END:variables
}
